# Generated by Django 4.2.7 on 2023-11-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='Ghost User', max_length=16, null=True)),
                ('last_name', models.CharField(default='Phantom User', max_length=16)),
                ('age', models.IntegerField(default=1)),
                ('weight', models.FloatField(default=1.5)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
