# Generated by Django 4.2.7 on 2023-11-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='stadium',
            name='location',
            field=models.CharField(default='Direccion del estadio', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='director',
            field=models.CharField(default='Director a cargo', max_length=30),
        ),
    ]
