# Generated by Django 4.2.7 on 2023-11-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_team_supervisor_stadium_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
