# Generated by Django 4.2.7 on 2023-11-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_league_status_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.CharField(default='No total de jugadores', max_length=60),
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
