# Generated by Django 4.2.7 on 2023-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_team_players_delete_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
