# Generated by Django 4.2.7 on 2023-11-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_city_status_stadium_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='stadium',
        ),
    ]
