# Generated by Django 4.2.7 on 2023-12-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_city_stadium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='team',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='location',
        ),
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stadium',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='Nombre del equipo', max_length=50),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Nombre del jugador', max_length=50)),
                ('number', models.IntegerField(default='Numero de jugador')),
                ('position', models.CharField(default='Posicion del jugador', max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
