# Generated by Django 4.2.7 on 2023-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_city_team_remove_stadium_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(default='Numero de jugador', verbose_name=100),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name=110000),
        ),
    ]
