# Generated by Django 4.2.7 on 2023-12-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_stadium_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=110000, verbose_name='Capacidad'),
        ),
    ]
