# Generated by Django 4.2.7 on 2023-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_player_number_alter_stadium_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.IntegerField(default=0),
        ),
    ]
